# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "debian/buster64"
  config.vm.network "private_network", ip: "192.168.10.200"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "buildroot", "/usr/src/buildroot", type: "nfs"
  config.vm.synced_folder "package", "/usr/src/package", type: "nfs"
  config.vm.provision "shell", path: "../vagrant/provision.sh"
end
